name: samudera
description: "The stock market made accessible!"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  hive: ^2.2.3
  lottie: ^3.3.2
  google_nav_bar: ^5.0.7
  super_bullet_list: ^0.0.3
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Garet
      fonts:
        - asset: assets/fonts/Garet-Book.ttf
          weight: 400
        - asset: assets/fonts/Garet-Heavy.ttf
          weight: 900

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic
